In [199]:
import numpy as np
np.__version__

'1.24.4'

- `NumPy` is short for Numerical Python. 
- There is internal documentation. To access it type `np?`

In [200]:
L1=list(range(2,10,2))
L1

[2, 4, 6, 8]

In [201]:
L2=[str(c) for c in L1]
print(L2)
print('L2[0]=',L2[0], ' is of type: ',type(L2[0]))

['2', '4', '6', '8']
L2[0]= 2  is of type:  <class 'str'>


In [202]:
L3=[True,0,3,5,'a']
print(L3)
[type(items) for items in L3]

[True, 0, 3, 5, 'a']


[bool, int, int, int, str]

**Exercise :** Create a list of numbers starting from 0 to 100 in steps of 10.

In [203]:
L4=list(range(0,101,10))
L4

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

Read the following code and guess its output. Then run and see whether your guess was correct.
```
[[c,c+1,c+2] for c in [0, 4, 7]]
```

`[[0,1,2]]` is wrong because  
`[0,4,7]` is a *list* and not *range(st,en,step)*

In [204]:
[[c, c+1,c+2] for c in [0, 4, 7]]

[[0, 1, 2], [4, 5, 6], [7, 8, 9]]

### Why numpy?

- less memory required
- faster

All elements of NumPy arrays will be of same type.

### Creating NumPy arrays from python list

In [205]:
L=list(range(100))
N=np.array(L)
print(N)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


If there are different data types in the list, then NumPy will upcast if possible.  
In the following example integers are converted to float.

In [206]:
[type(l) for l in [1, 4.2,7,9.2]]

[int, float, int, float]

In [207]:
N=np.array([1,4.2,7,9.2])
print(N)
[type(n) for n in N]

[1.  4.2 7.  9.2]


[numpy.float64, numpy.float64, numpy.float64, numpy.float64]

We can explicitly set data type using keyword `dtype`.

In [208]:
N=np.array([1,2,3,4], dtype='float')
print(N)
[type(n) for n in N]

[1. 2. 3. 4.]


[numpy.float64, numpy.float64, numpy.float64, numpy.float64]

**Exercise:** What will happen if in the previous example `dtype` is set to `int`?  
- Truncates digits after decimal point

In [209]:
N = np.array([1.8, 2.1, 7.88, 3.9999999999, -1.3, -6.9999], dtype='int')
N

array([ 1,  2,  7,  3, -1, -6])

In [210]:
N = np.array([1.8, 2, 7.88, 3.9999999999, -1, -6.9999], dtype='complex')
N

array([ 1.8   +0.j,  2.    +0.j,  7.88  +0.j,  4.    +0.j, -1.    +0.j,
       -6.9999+0.j])

**Multidimensional arrays:** We can create multidimensional arrays in numpy from *nested lists*.

In [211]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

**Exercise :** Modify the following code to make it a 5x5 square array.

```
   np.array([range(i, i + 3) for i in [2, 4, 6, 8, 10]])
```

In [212]:
np.array([range(i,i+5) for i in [2,4,6,8,10]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10],
       [ 8,  9, 10, 11, 12],
       [10, 11, 12, 13, 14]])

### Creating numpy arrays with zeros, ones or full

In [213]:
# Create an array of 10 zeros of `int` type. Try changing it to float.
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [214]:
np.zeros(10, dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [215]:
# Create a 4X5 array of zeros of 'float' type
np.zeros((4,5), dtype='float')  #(4,5) indicates 4 rows 5 cols

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [216]:
# Create an array of 10 ones of `int` type.
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [217]:
# Create an array of 10 PI s
np.full(10,np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

**Exercise :** Create a 4X5 array of ones of 'float' type

In [218]:
np.ones((4,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Exercise :** Create a 4X5 array of 12.12

In [219]:
np.full((4,5), 12.12)

array([[12.12, 12.12, 12.12, 12.12, 12.12],
       [12.12, 12.12, 12.12, 12.12, 12.12],
       [12.12, 12.12, 12.12, 12.12, 12.12],
       [12.12, 12.12, 12.12, 12.12, 12.12]])

**Exercise :** Create a 3x4X5 array of 12.12

In [220]:
np.full((3,4,5), 12.12)  # 3 matrices with 4 rows and 5 columns each

array([[[12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12]],

       [[12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12]],

       [[12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12],
        [12.12, 12.12, 12.12, 12.12, 12.12]]])

### Create an array with arange

In [221]:
N=np.arange(1,20,3)
print(type(N))
N

<class 'numpy.ndarray'>


array([ 1,  4,  7, 10, 13, 16, 19])

### Create an array with linspace

In [222]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Identity matrix and empty array

In [223]:
np.eye(5) #5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [224]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Attributes of NumPy Arrays

Each numpy array has several attributes: `ndim` (the number of dimensions), `shape` (the size of each dimension), and `size` (the total size of the array) etc.

In [225]:
A=np.ones((2,5,3), dtype='float')
A

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [226]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

3
(2, 5, 3)
30
float64


In [227]:
B=np.full((2,2,2,2), 5)
B

array([[[[5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5]]],


       [[[5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5]]]])

In [228]:
print(B.ndim)
print(B.shape)
print(B.size)
print(B.dtype)

4
(2, 2, 2, 2)
16
int32


# Indexing an array

A[...,row_index, column_index]

Indices starts from 0. Eg:- In a 2x3 array, row_index takes values 0 (first row) and 1 (second row); column_index takes values 0(first column), 1(second column) and 2(third column).

In [229]:
A=np.arange(1,10)
print(A)
print(A[0])

[1 2 3 4 5 6 7 8 9]
1


In [230]:
try:
    A[10]
except Exception as e:
    print(e.__class__.__name__)

IndexError


In [231]:
# Access last element
A[-1]

9

**Exercise :** Print first and last index of A

In [232]:
print(A)
print(A[0], A[-1])

[1 2 3 4 5 6 7 8 9]
1 9


In [233]:
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(B)
B[0, 1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

**Exercise :** What are the index of 4, 6 and 10 in B?

In [234]:
print(B[0,-1], B[1,1], B[-1,1])

4 6 10


**Exercise:** What wouuld be the output of B[-1,-2]?  
- 11

In [235]:
B[-1,-2]

11

### Array slicing

A[start:stop:step]

B[start:stop:step, start:stop:step]

By default, start value is zero, stop value is last value and step is assumed to be one.

In [236]:
A = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 12, 13], [14, 15, 16]]])
print(A.shape)
A

(2, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [237]:
A[-1,-1,-1]

16

In [238]:
A = list(range(1,10))
print(A,A[:],A[::], sep='\n')
print(A[7])
print(A[2:7]) #A[7] = 8 is NOT INCLUDED

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
8
[3, 4, 5, 6, 7]


In [239]:
print(A[:7])
print(A[-1:-5:-1])

[1, 2, 3, 4, 5, 6, 7]
[9, 8, 7, 6]


In [240]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Exercise:** Create a sub square array from B, containing `[[2,3],[6,7]]`.

In [241]:
B[0:2 , 1:3]  # row= 0,1 , col=1,2 elements B[0,1], B[0,2], B[1.1], B[1,2]

array([[2, 3],
       [6, 7]])

**Exercise :** Access first column and second last column of B.

In [242]:
print(B[:,0:1], end='\n\n')
print(B[:, -1:])

[[1]
 [5]
 [9]]

[[ 4]
 [ 8]
 [12]]


In [243]:
print(B[:,0], B[:,0].shape, B[:,0].ndim, end='\n\n')
print(B[:, 0:1], B[:, 0:1].shape,B[:,0:1].ndim)

[1 5 9] (3,) 1

[[1]
 [5]
 [9]] (3, 1) 2


**Exercise:** Create a sub square array from B, containing `[[2,10][4,12]]`

In [244]:
print(B)
print(B[::2, 1::2].transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2 10]
 [ 4 12]]


### Reshaping of arrays

One can reshape an array using `reshape` method.

In [245]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(A)
A.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [246]:
A=A.reshape(3,3)
print(A)
A.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [247]:
print(B)
print(B.shape,end='\n\n')
B=B.reshape(2,6)
print(B)
print(B.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [248]:
B=B.reshape(B.size,) #Straighten
print(B)
B.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12]


(12,)

### Concatenation (joining together)
Joining of two arrays in NumPy, is primarily accomplished using the routines  
np.concatenate, np.vstack, and np.hstack.

In [249]:
x1 = np.array([[1, 2,3,4],[5,6,7,8]])
x2 = np.array([[9, 10,11,12],[13,14,15,16]])
print('X1:\n',x1)
print('\nX2:\n',x2)

X1:
 [[1 2 3 4]
 [5 6 7 8]]

X2:
 [[ 9 10 11 12]
 [13 14 15 16]]


In [250]:
x3 = np.concatenate((x1, x2))  # adds X2 as subsequent rows to x1 BUT x1,x2 are not modified
x3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [251]:
x4 = np.concatenate((x1,x2), axis=1) # adds x2 as subsequent columns to x1 BUT x1,x2 are not modified
x4

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### Copying an array

In [252]:
x5 = x2.copy()  # This is how we copy (new copy) arrays to a variable.
x5  
# x5 = x2[0] copies by reference

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [253]:
N1=np.array([1,2,3])
N2=N1.copy() #using .copy()
print('N1:',N1)
print('N2:', N2)
N2[0]=99
print('N1:', N1)
print('N2:', N2)
N3=N1 #assigning directly
print('N1:', N1)
print('N3:', N3)
N3[0] = 99
print('N1:', N1)
print('N3:', N3) #both N1[0] and N3[0] are modified

N1: [1 2 3]
N2: [1 2 3]
N1: [1 2 3]
N2: [99  2  3]
N1: [1 2 3]
N3: [1 2 3]
N1: [99  2  3]
N3: [99  2  3]


`np.vstack` and `np.hstack` are used if we have two arrays of different dimensions.

In [254]:
np.vstack((x1, x5))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [255]:
np.hstack((x1,x5))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

## NumPy allows us to write shorter codes

**Exercise:** Write a function to return reciprocals of a list of numbers without and using functionalities of numpy.

In [256]:
# Without numpy method-1
def reciprocal_list(LL):
    output = []
    for l in LL:
        output.append(1./l)
    return output

In [257]:
A = range(1, 11)
reciprocal_list(A)  # Took six lines

[1.0,
 0.5,
 0.3333333333333333,
 0.25,
 0.2,
 0.16666666666666666,
 0.14285714285714285,
 0.125,
 0.1111111111111111,
 0.1]

In [258]:
# Using numpy array
A = np.arange(1, 11)
1./A  # Just one line!

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

### NumPy is faster too!

In [259]:
#Without numpy - method-1
A = np.arange(1.,100000)
%timeit -n 100 reciprocal_list(A)

31.7 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [260]:
#Without numpy - method-2
%timeit -n 100 [1/x for x in range(1,100001)]

11.7 ms ± 539 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [261]:
#With numpy
%timeit -n 100 1./A

72.4 µs ± 3.33 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


The method using NumPy is faster.  
In this approach reciprocal is applied to the entire array instead of applying it to each element separately.  
This approach is called **vectorization**.  

**Important lesson from previous exercise is "Never use loops if you can use vectorization in NumPy"**

Vectorization makes code readable and faster.  
Formulas can be implemented very conveniently.

### Vectorized arithmetical Operations

In [262]:
x=np.arange(5)
print('x =',x)
print('x + 5 =',x+5)
print('x - 5 =',x-5)
print('x * 2 =',x*2)
print('x / 2 =', x / 2)
print('x // 2 =', x // 2)  # floor division
print('-x =',-x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x = [0 1 2 3 4]
x + 5 = [5 6 7 8 9]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]
x / 2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
-x = [ 0 -1 -2 -3 -4]
x ** 2 =  [ 0  1  4  9 16]
x % 2  =  [0 1 0 1 0]


### Vectoried trigonometric operations

In [263]:
theta = np.linspace(0, np.pi, 3)

In [264]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [265]:
np.sin(np.deg2rad(30))

0.49999999999999994

In [266]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]


In [267]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log10(x) = [0.         0.30103    0.60205999 1.        ]


### Min, Maximum, Std. Dev. etc.

In [273]:
A = np.random.rand(5)  # Creates an array of 10 random numbers
print(A)

[0.06885756 0.13313564 0.95164895 0.11102319 0.58767385]


In [274]:
print('Sum:', A.sum())
print('Max:', A.max())
print('Min:', A.min())
print('Mean:',A.mean())
print('Std Dev:', A.std())

Sum: 1.852339194609772
Max: 0.9516489537690773
Min: 0.06885756372329366
Mean: 0.3704678389219544
Std Dev: 0.34628219532899984


**Exercise**. A fair unbiased coin can be modelled using `np.random`.  
Understand the code and then modify it to make it a biased coin which gives head 60% of the time.

In [279]:
x=np.random.rand(100000)

In [282]:
# Results from coin toss of a fair coin can be modelled as :
H=np.sum(x>0.5)
T=x.size-H
print("Number of heads = ", H)
print("Number of tails = ", T)

Number of heads =  50430
Number of tails =  49570


In [283]:
#method-1
H=np.sum(x>0.4) #biased coin simulation
T=x.size-H
print("Number of heads = ", H)
print("Number of tails = ", T)

Number of heads =  60180
Number of tails =  39820


In [288]:
#method-2
result = np.random.choice([1,0], size=100000, p=[0.6, 0.4])
H=result.sum()
T=result.size-H
print("Number of heads = ", H)
print("Number of tails = ", T)

Number of heads =  59927
Number of tails =  40073
